import java.io.*;
class instructions
{
    public void ins()throws Exception
      {
        System.out.println("MASTERMIND\nTHE BATTLE TO BREAK THE CODE\nIt is a challenging game, which improves concentration, thinking capacity.\nIt is  an addictive and interesting game\n");
        System.out.println("OBJECT OF THE GAME\nthe object of MASTERMIND is to guess a secret code or master code \nconsisting of a series of 3,4 or 5 digits(based on the difficulty) \nranging from 1 to 5, 1 to 7, or 1 to 8 respectively. \neach guess results in feedback narrowing down the possibilities of the code.");
        System.out.println("If the player fails to guess the secret code within the number \nof chances provided, he loses the game.\n");
        Thread.sleep(25000);
        System.out.println("\nIn single player mode, the computer generates a 3,4 or 5 digit secret code or master code \nwhich is any combination of the 5 digits (1-5), 7 digits (1-7) or eight digits (1-8) \ndepending on the level of difficulty.");
        System.out.println("The player has to enter combinations of numbers and attempt to duplicate the exact digits \nand positions of the digits as in the master code.");
        Thread.sleep(15000);
        System.out.println("\nThe computer responds to the combination generated by the player every time, by displaying \n'o' -to indicate that one of the digit is right and correctly positioned and \n'x'-to indicate that one of the digit present in the players code is correct but not correctly positioned ");
        System.out.println("(without indicating which digit corresponds to it).");
        Thread.sleep(15000);
        System.out.println("\nThe key symbols does not indicate which digit is correctly positioned or correct, \nit just indicates that one of the digit in the combination is correctly positioned or correct. \nIt is the part of the challenge of the game for the player to figure out which digit corresponds to particular key symbol.");
        Thread.sleep(30000);
        System.out.print("\u000c");
        System.out.println("The player keeps entering combinations of digits and getting feedback from the computer until he guesses the code exactly. \nWhen the player guesses the master code the feedback is all 'o's and the Master code is revealed.\n");
        Thread.sleep(10000);
        System.out.println("This game has  3 difficulty levels,");
        System.out.println("   •In level 1, the master code is of three digits, from 1 to 5 and the player gets 8 chances to guess the master code.");
        System.out.println("   •In level 2, the master code is of four digits from 1 to 7 and gets 10 chances to guess the master code.");
        System.out.println("   •In level 3, the master code is of five digits from 1 to 8 and gets 12 chances to guess the master code.");
        System.out.println("If player clears level 1, he is promoted to level 2, and then to level 3.he is even free to choose his level of difficulty.");   
        Thread.sleep(15000);
        System.out.println("\nIn dual mode, there are two players, player1 and player2, where player1 is the code breaker \n(who attempts to crack the master code), player2  is the code maker \n(who generates the master code i.e. he does the work of computer)\n.Once the player1 breaks the code, the players switch their roles.");
        System.out.println("\nIn multiplayer mode, in which the computer generates the master code for all the players. \nThe player who breaks the master code in minimum number of chances, wins the game. \nThe maximum number of players that can play at a time is 3.");
        System.out.println("The player who gets the maximum points (who breaks the code in minimum number of chances) wins the game.\n");
        Thread.sleep(20000);
        BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Press enter key to continue...");
        br.read();
        System.out.print("\u000C");
        menu.options();
      }
}
